--find total customers by Countries
SELECT 
	country,
	count(customer_key) AS Total_customers
FROM gold.dim_customer
GROUP BY country
ORDER BY count(customer_key) DESC;

--find total customers by gender
SELECT 
	gender,
	count(customer_key) AS Total_customers
FROM gold.dim_customer
GROUP BY gender
ORDER BY count(customer_key) DESC;

--find total product by category
SELECT 
	category,
	count(product_key) AS Total_customers
FROM gold.dim_products
GROUP BY category
ORDER BY count(product_key) DESC;

--find average cost by category
SELECT 
	category,
	AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY AVG(cost) DESC;

--find average cost by category
SELECT 
	category,
	AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY AVG(cost) DESC;

--find average cost by category
SELECT 
	p.category,
	sum(f.sales_amount) As total_revenue
FROM gold.fact_sales f
LEFT JOIN 
gold.dim_products p
ON f.product_key =p.product_key
GROUP BY p.category
ORDER BY sum(f.sales_amount) DESC;

--what is the total revenue generated by each customer
SELECT
	c.customer_id,
	c.first_name,
	c.last_name,
	sum(f.sales_amount) As total_revenue
FROM gold.fact_sales f
LEFT JOIN 
gold.dim_customer c
ON f.customer_key =c.customer_key
GROUP BY c.customer_id,
	c.first_name,
	c.last_name
ORDER BY sum(f.sales_amount) DESC;

-- What is the distribution of sold item across countries
SELECT
	c.country,
	sum(f.quantity) As total_solditems
FROM gold.fact_sales f
LEFT JOIN 
gold.dim_customer c
ON f.customer_key =c.customer_key
GROUP BY c.country
ORDER BY sum(f.quantity) DESC;
